### ISSUE TITLE
Šumniki

### ISSUE THREAD

**Issue by timotejvesel** [BarbaraPal/APPR-2020-21#1]
Opazil sem, da v imenih stolpcev uporabljaš šumnike (npr. `DRŽAVA`, `DELEŽ`). Bolje bo, da se temu izogibaš in se omejiš na znake angleške abecede. Podobno bo tudi za imena datotek bolje, da se šumnikov izogibaš. 

Poleg tega tabel ne rabiš shranjevati v `csv` datoteko in jih nato v datoteki `vizualizacija.r` uvoziti iz shranjene `csv` datoteke in shraniti v novo spremenljivko, saj imaš s tem tabele podvojene. Na primer tabeli `shrani.delo` ter `delo` sta popolnoma enaki. Namesto tega lahko v `uvoz.r` definiraš tabelo `delo` 
```r
delo <- uvoz.delo()
```
in nato to tabelo uporabljaš naprej pri vizualizaciji. Če želiš lahko tabelo tudi shraniš 
```r
delo <- uvoz.delo() %>%
  write_csv("podatki/delo.csv", na= "NA", append = FALSE, col_names = TRUE),
```
vendar je potem v datoteki `vizualizacija.r` ne rabiš še enkrat  uvoziti iz shranjene `csv` datotek ter definirati z drugim imenom , saj jo definiraš že z zgornjim klicem.  Tabelo lahko uporabljaš v vseh datotekah iz projekta, ne le v tisti, v katerih jo definiraš.

**Comment by BarbaraPal** [comment]
Hvala za komentar, sem popravila.
